dist: trusty
language: scala

scala:
  - 2.11.12
  - 2.12.4

jdk:
  - oraclejdk8

addons:
  postgresql: "9.5"

services:
  - postgresql

sbt_args: -J-Xmx4096M

env:
  - PG_HOST_PORT=127.0.0.1:5432 PG_USER=postgres PG_DBNAME=finagle_postgres_test

before_script:
  - createdb -U postgres finagle_postgres_test
  - psql -U postgres -c "CREATE EXTENSION IF NOT EXISTS hstore" finagle_postgres_test
  - psql -U postgres -c "CREATE EXTENSION IF NOT EXISTS citext" finagle_postgres_test

script:
  - sbt ++$TRAVIS_SCALA_VERSION coverage test

after_success:
  - sbt coveralls

